/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMULARIOS;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author EMERITA
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        txtcedula.setVisible(false);
        cerrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deskPricipal = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cargo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuherramientas = new javax.swing.JMenu();
        menuventa = new javax.swing.JMenuItem();
        menucompra = new javax.swing.JMenuItem();
        menuPersonal = new javax.swing.JMenu();
        menucliente = new javax.swing.JMenuItem();
        menuproveedor = new javax.swing.JMenuItem();
        menuusuario = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuproductos = new javax.swing.JMenu();
        menuproducto = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuinformes = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menusalir = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout deskPricipalLayout = new javax.swing.GroupLayout(deskPricipal);
        deskPricipal.setLayout(deskPricipalLayout);
        deskPricipalLayout.setHorizontalGroup(
            deskPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        deskPricipalLayout.setVerticalGroup(
            deskPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ventaMenu.png"))); // NOI18N
        jButton1.setText("Realizar Venta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/usuarioMenu.png"))); // NOI18N
        btnCliente.setText("Registrar Cliente");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/reporteMenu.png"))); // NOI18N
        jButton3.setText("Informe Ventas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Usuario : ");

        usuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        usuario.setText("yesid sanchez");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Cargo : ");

        cargo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cargo.setText("Administrador");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/shopcart.png"))); // NOI18N

        txtcedula.setText("jTextField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usuario))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cargo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        menuherramientas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/toolsMenu.png"))); // NOI18N
        menuherramientas.setText("Herramientas");

        menuventa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuventa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ventaMenu.png"))); // NOI18N
        menuventa.setText("Venta");
        menuventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuventaActionPerformed(evt);
            }
        });
        menuherramientas.add(menuventa);

        menucompra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        menucompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/compraMenu.png"))); // NOI18N
        menucompra.setText("Compra");
        menucompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucompraActionPerformed(evt);
            }
        });
        menuherramientas.add(menucompra);

        jMenuBar1.add(menuherramientas);

        menuPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/usuarioMenu.png"))); // NOI18N
        menuPersonal.setText("Personal");

        menucliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        menucliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/usuarioMenu.png"))); // NOI18N
        menucliente.setText("Clientes");
        menucliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuclienteActionPerformed(evt);
            }
        });
        menuPersonal.add(menucliente);

        menuproveedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        menuproveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/usuarionegro.png"))); // NOI18N
        menuproveedor.setText("Proveedores");
        menuproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuproveedorActionPerformed(evt);
            }
        });
        menuPersonal.add(menuproveedor);

        menuusuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        menuusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/usuarioA.png"))); // NOI18N
        menuusuario.setText("Usuarios");
        menuusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuusuarioActionPerformed(evt);
            }
        });
        menuPersonal.add(menuusuario);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/workers.png"))); // NOI18N
        jMenuItem4.setText("Roles");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuPersonal.add(jMenuItem4);

        jMenuBar1.add(menuPersonal);

        menuproductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/codigoMenu.png"))); // NOI18N
        menuproductos.setText("Productos");

        menuproducto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        menuproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Agregarr.png"))); // NOI18N
        menuproducto.setText("Productos");
        menuproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuproductoActionPerformed(evt);
            }
        });
        menuproductos.add(menuproducto);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/NombreProducto.png"))); // NOI18N
        jMenuItem3.setText("Categoria");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuproductos.add(jMenuItem3);

        jMenuBar1.add(menuproductos);

        menuinformes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/reporteMenu.png"))); // NOI18N
        menuinformes.setText("Informes");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/DescProd.png"))); // NOI18N
        jMenuItem1.setText("Informe Ventas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuinformes.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/reporteMenu.png"))); // NOI18N
        jMenuItem2.setText("Informe Compra");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuinformes.add(jMenuItem2);

        jMenuBar1.add(menuinformes);

        menusalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/desplegar1.png"))); // NOI18N
        menusalir.setText("Opciones");
        menusalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menusalirActionPerformed(evt);
            }
        });

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/exitMenu.png"))); // NOI18N
        jMenuItem5.setText("Cerrar Sesion");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menusalir.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ayuda.png"))); // NOI18N
        jMenuItem6.setText("Ayuda");
        jMenuItem6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem6MouseClicked(evt);
            }
        });
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menusalir.add(jMenuItem6);

        jMenuBar1.add(menusalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deskPricipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deskPricipal)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public  void cerrar(){
         try {
             this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
             addWindowListener(new WindowAdapter(){
             public void windowClosing(WindowEvent e){
                 confirmarsalida();
             }
             });
             
         } catch (Exception e) {
             e.printStackTrace();
         }
    
     }
     public void confirmarsalida(){
         int valor = JOptionPane.showConfirmDialog(this, "¿Seguro que desea cerrar?","Advertencia",JOptionPane.YES_NO_OPTION);
         if (valor == JOptionPane.YES_OPTION){
             JOptionPane.showMessageDialog(null, "Gracias por su visita");
             this.dispose();
         }
     }
    private void menuclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuclienteActionPerformed
        // TODO add your handling code here:
        Cliente form = new Cliente();
        deskPricipal.add(form);
        form.setClosable(true);
        form.setIconifiable(true);
        try {
            form.setMaximum(true);
        } catch (Exception e) {
        }

        form.toFront();
        form.setVisible(true);
       // this.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuclienteActionPerformed

    private void menuusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuusuarioActionPerformed
        // TODO add your handling code here:
         Empleado form = new Empleado();
        deskPricipal.add(form);
        form.setClosable(true);
        form.setIconifiable(true);
        try {
            form.setMaximum(true);
        } catch (Exception e) {
        }

        form.toFront();
        form.setVisible(true);
        
    }//GEN-LAST:event_menuusuarioActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        FrmMostrarVentas ventas = new FrmMostrarVentas();
        deskPricipal.add(ventas);
        ventas.setClosable(true);
        ventas.setIconifiable(true);
        try {
            ventas.setMaximum(true);
        } catch (Exception e) {
        }
        ventas.toFront();
        ventas.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        // TODO add your handling code here:
        Cliente form1 = new Cliente();
        deskPricipal.add(form1);
        form1.setClosable(true);
        form1.setIconifiable(true);
        try {
            form1.setMaximum(true);
        } catch (Exception e) {
        }

        form1.toFront();
        form1.setVisible(true);
        
    }//GEN-LAST:event_btnClienteActionPerformed

    private void menuproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuproveedorActionPerformed
        // TODO add your handling code here:
         Proveedor form1 = new Proveedor();
        deskPricipal.add(form1);
        form1.setClosable(true);
        form1.setIconifiable(true);
        try {
            form1.setMaximum(true);
        } catch (Exception e) {
        }

        form1.toFront();
        form1.setVisible(true);
    }//GEN-LAST:event_menuproveedorActionPerformed

    private void menuproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuproductoActionPerformed
        // TODO add your handling code here:
        Producto form1 = new Producto();
        deskPricipal.add(form1);
        form1.setClosable(true);
        form1.setIconifiable(true);
        try {
            form1.setMaximum(true);
        } catch (Exception e) {
        }
        form1.toFront();
        form1.setVisible(true);
    }//GEN-LAST:event_menuproductoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        FrmMostrarVentas ventas = new FrmMostrarVentas();
        deskPricipal.add(ventas);
        ventas.setClosable(true);
        ventas.setIconifiable(true);
        try {
            ventas.setMaximum(true);
        } catch (Exception e) {
        }
        ventas.toFront();
        ventas.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Categorias form1 = new Categorias();
        form1.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Roless rol = new Roless();
        rol.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void menuventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuventaActionPerformed
        // TODO add your handling code here:
        FrmVentaDetalle form1 = new FrmVentaDetalle();
        deskPricipal.add(form1);
        form1.setClosable(true);
        form1.setIconifiable(true);
        try {
            form1.setMaximum(true);
        } catch (Exception e) {
        }
        form1.toFront();
        form1.setVisible(true);
                
    }//GEN-LAST:event_menuventaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FrmVentaDetalle form1 = new FrmVentaDetalle();
        deskPricipal.add(form1);
        form1.setClosable(true);
        form1.setIconifiable(true);
        try {
            form1.setMaximum(true);
        } catch (Exception e) {
        }
        form1.toFront();
        form1.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void menusalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menusalirActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menusalirActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        dispose();
        
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem6MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem6MouseClicked

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
           
         JOptionPane.showMessageDialog(null, "ATAJOS DE TECLADO\n"
                + "MENU\n"
                + "F1 = abrir formulario Venta\n"
                + "F2 = Compra\n"
                + "Ctrl + C = clientes\n"
                + "Ctrl + U =  usuarios\n"
                + "Ctrl + C = proveedores\n"
                + "Ctrl + R = Roles\n"
                + "Alt + P = Productos\n"
                + "Alt + T = Categorias\n"
                + "Alt + V = Informe de Ventas\n"
                + "Alt + C = Informe de Compras\n"
                + "Ctrl + S = Cerrar Sesion\n"
                + "Ctrl + A = Ayuda\n"        
        );
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
       
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menucompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucompraActionPerformed
        // TODO add your handling code here:
        
        FrmCompraDetalle form1 = new FrmCompraDetalle();
        deskPricipal.add(form1);
        form1.setClosable(true);
        form1.setIconifiable(true);
        try {
            form1.setMaximum(true);
        } catch (Exception e) {
        }
        form1.toFront();
        form1.setVisible(true);
    }//GEN-LAST:event_menucompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliente;
    public static javax.swing.JLabel cargo;
    private javax.swing.JDesktopPane deskPricipal;
    private javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JMenu menuPersonal;
    private javax.swing.JMenuItem menucliente;
    private javax.swing.JMenuItem menucompra;
    public static javax.swing.JMenu menuherramientas;
    public static javax.swing.JMenu menuinformes;
    private javax.swing.JMenuItem menuproducto;
    public static javax.swing.JMenu menuproductos;
    private javax.swing.JMenuItem menuproveedor;
    private javax.swing.JMenu menusalir;
    private javax.swing.JMenuItem menuusuario;
    private javax.swing.JMenuItem menuventa;
    public static javax.swing.JTextField txtcedula;
    public static javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
